[package]
name = "mpw"
version = "0.1.0"
authors = ["Dario Goetz <dario.goetz@googlemail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12"
sha2 = "0.10"
scrypt = "0.11"
